fallback = "index.html"
404 = "index.html"

[[headers]] # cache assets for 10 mins
name = "cache-control"
value = "public, max-age=600"
on = "^/assets/"

[[forms]]
from = "/contact"
to = "support@vitahub.app"
then = "/ty"
