
import { CVData } from '../types/cv';

// This would be the file generated by our build-time processing
import generatedCVs from '../data/generated/cvs.json';

/**
 * Load CV data for a specific person and language
 */
export function loadCV(personName: string, languageCode: string = 'en'): CVData | null {
  if (!generatedCVs || !generatedCVs[personName]) {
    console.error(`CV data for ${personName} not found`);
    return null;
  }
  
  // Get the CV data for the specified language, fall back to english
  const cvData = generatedCVs[personName][languageCode] || generatedCVs[personName]['en'];
  
  if (!cvData) {
    console.error(`CV data for ${personName} in language ${languageCode} not found`);
    return null;
  }
  
  return cvData as CVData;
}

/**
 * Get all available CV names
 */
export function getAvailableCVs(): string[] {
  return Object.keys(generatedCVs || {});
}

/**
 * Get available languages for a specific CV
 */
export function getAvailableLanguagesForCV(personName: string): string[] {
  if (!generatedCVs || !generatedCVs[personName]) {
    return [];
  }
  
  return Object.keys(generatedCVs[personName]);
}
